### ISSUE TITLE
Add Kafka scripts

### ISSUE THREAD

**Issue by geoand** [geoand/quarkus-java17-demo#2]
@cescoffier did you have some scripts ready to go, or should I just add some based on your other repositories?

**Comment by cescoffier** [comment]
I have docker compose files, let me add that.

**Comment by geoand** [comment]
Thanks!

**Comment by cescoffier** [comment]
Fixed.

BTW, you can also use the dev service for Kafka.

**Comment by geoand** [comment]
Thanks!

> BTW, you can also use the dev service for Kafka.

But that does not play well when one has multiple services, no?

**Comment by cescoffier** [comment]
Of course it works! The service is shared between the different applications.

**Comment by geoand** [comment]
That's nice!

I wasn't aware that the service could be shared. It is still zero config for both services?

**Comment by cescoffier** [comment]
Yes, no config. 
The first one starts it, the second one uses it.

**Comment by geoand** [comment]
That is amazing!
